### Preparación de ambiente

#### Lectura de archivos desde S3

In [ ]:
!pip3 install boto3

In [ ]:
import os

import boto3
import pandas as pd


AWS_S3_BUCKET = "g6-datalake-proyectointegrador"
AWS_ACCESS_KEY_ID = "ASIA3T2YJ54QMMRGILWT"
AWS_SECRET_ACCESS_KEY = "Dr8iICRJJk9aJi8atKj0nLJXJRh/qtfTf8ugSX8f"
AWS_SESSION_TOKEN = "FwoGZXIvYXdzEC4aDG1QURO1yU/tAWQqBiLIAZmRaFPqbKGNFEfzb2u0NgJ4UuEgU5n1wmwa3EKrurUwuQvptotqPmZoMjzExLEmgSljb/tKkEx3TdjMbIpvTjGz+zvEAtOUK9jdjzGXv8drLKyZoSd1uA0i/UdLG2h5gmZr6gMDNlhK7YFNCJ86aBhsUL5/xb/AJTL19uLLnHNDMqGXkLO064zk/1T8vcCG9+edjzYvkotprbl1Ds+zbqUN91u9bflpqFa7jCoPMYLAC0g+MupfvIrh74XknGn+1E5zBA1YJeMjKNOGi5UGMi3SMjRomuPGxylmjoqtH9w1hGk8hf8NegGholc0JoO20hXi4gQr03/1IDc2NuQ="

s3_client = boto3.client(
    "s3",
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    aws_session_token=AWS_SESSION_TOKEN,
)

response = s3_client.get_object(Bucket=AWS_S3_BUCKET, Key="03_TrustedZone/03_TablaUnida.csv")

status = response.get("ResponseMetadata", {}).get("HTTPStatusCode")

if status == 200:
    print(f"Successful S3 get_object response. Status - {status}")
    df = pd.read_csv(response.get("Body"), encoding='UTF-8')
    print(df)
else:
    print(f"Unsuccessful S3 get_object response. Status - {status}")

In [ ]:
import pandas as pd

## Modelado

In [ ]:
describe = df.describe()
describe

Unnamed: 0    codproyecto        estrato           area  \
count  709339.000000  709339.000000  709339.000000  709339.000000   
mean   354669.000000   60932.485534       4.773224     132.078819   
std    204768.675635     553.061970       1.004529     311.851385   
min         0.000000   60000.000000       2.000000      20.000000   
25%    177334.500000   60469.000000       4.000000      66.800000   
50%    354669.000000   60899.000000       5.000000      87.000000   
75%    532003.500000   61388.000000       6.000000     128.000000   
max    709338.000000   62615.000000       6.000000   12187.000000   

                alc.          baños     area patio  area lote / jardin  \
count  709339.000000  709339.000000  709339.000000       709339.000000   
mean        2.617692       2.422721       0.535342            3.573475   
std         0.728180       0.966115       4.851356           45.346404   
min         0.000000       0.000000       0.000000            0.000000   
25%         2.000000       2.000000       0.000000            0.000000   
50%         3.000000       2.000000       0.000000            0.000000   
75%         3.000000       3.000000       0.000000            0.000000   
max         4.000000       6.600000      90.000000         3171.000000   

       area terraza o balcon  estudio/estar  ...          Vent.  \
count          709339.000000  709339.000000  ...  709339.000000   
mean                8.495185       0.715955  ...       0.988454   
std                50.706554       0.450959  ...       0.106830   
min                 0.000000       0.000000  ...       0.000000   
25%                 0.000000       0.000000  ...       1.000000   
50%                 2.000000       1.000000  ...       1.000000   
75%                 6.000000       1.000000  ...       1.000000   
max              2777.000000       1.000000  ...       1.000000   

          Muros Bañ.         Activo  Gimnasio_Dotado  Gimnasio_Espacio  \
count  709339.000000  709339.000000    709339.000000     709339.000000   
mean        0.979924       0.103596         0.344371          0.000355   
std         0.140262       0.304737         0.475163          0.018845   
min         0.000000       0.000000         0.000000          0.000000   
25%         1.000000       0.000000         0.000000          0.000000   
50%         1.000000       0.000000         0.000000          0.000000   
75%         1.000000       0.000000         1.000000          0.000000   
max         1.000000       1.000000         1.000000          1.000000   

       Ofrece Piscina_Comunal  Ofrece Piscina_Privada  Saunas_Jacuzzi  \
count           709339.000000           709339.000000   709339.000000   
mean                 0.002523                0.000316        0.079058   
std                  0.050171                0.017768        0.269830   
min                  0.000000                0.000000        0.000000   
25%                  0.000000                0.000000        0.000000   
50%                  0.000000                0.000000        0.000000   
75%                  0.000000                0.000000        0.000000   
max                  1.000000                1.000000        1.000000   

        Saunas_Sauna   Saunas_Turco  
count  709339.000000  709339.000000  
mean        0.046274       0.237466  
std         0.210078       0.425531  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000  

[8 rows x 95 columns]

In [ ]:
df_num = df[['estrato','area','alc.','baños','area patio','area lote / jardin','area terraza o balcon','precio_deflacionado']]

In [ ]:
from sklearn.preprocessing import RobustScaler
import numpy as np

df_num = df_num.values
scaler = RobustScaler()
df_num=scaler.fit_transform(df_num)
m_cov = np.cov(df_num.T)


mu = np.median(df_num,axis=0)
inv_cov = np.linalg.pinv(m_cov)
mahal = []
for i, x in enumerate(df_num):
    dist = (x-mu).T.dot(inv_cov).dot(x-mu)
    mahal.append(dist)

In [ ]:
from scipy.stats import chi2

df['mahal_distance'] = mahal
df['p_value'] = 1 - chi2.cdf(df['mahal_distance'], df_num.shape[1])
df_c = df.loc[df.p_value > 0.1]
describe = df_c.describe()
describe

Unnamed: 0    codproyecto        estrato           area  \
count  645535.000000  645535.000000  645535.000000  645535.000000   
mean   349887.992623   60917.189429       4.776358     100.503074   
std    203203.122478     547.030142       0.990166      52.387260   
min         0.000000   60000.000000       2.000000      20.000000   
25%    175103.500000   60467.000000       4.000000      66.000000   
50%    348057.000000   60882.000000       5.000000      85.000000   
75%    523730.500000   61367.000000       6.000000     119.000000   
max    709338.000000   62615.000000       6.000000     460.000000   

                alc.          baños     area patio  area lote / jardin  \
count  645535.000000  645535.000000  645535.000000       645535.000000   
mean        2.652928       2.364108       0.106519            0.784832   
std         0.644770       0.834264       0.950404            7.066408   
min         1.000000       0.000000       0.000000            0.000000   
25%         2.000000       2.000000       0.000000            0.000000   
50%         3.000000       2.000000       0.000000            0.000000   
75%         3.000000       3.000000       0.000000            0.000000   
max         4.000000       5.000000      16.000000          130.000000   

       area terraza o balcon  estudio/estar  ...         Activo  \
count          645535.000000  645535.000000  ...  645535.000000   
mean                5.418089       0.716232  ...       0.097586   
std                12.552570       0.450826  ...       0.296754   
min                 0.000000       0.000000  ...       0.000000   
25%                 0.000000       0.000000  ...       0.000000   
50%                 2.000000       1.000000  ...       0.000000   
75%                 5.000000       1.000000  ...       0.000000   
max               167.000000       1.000000  ...       1.000000   

       Gimnasio_Dotado  Gimnasio_Espacio  Ofrece Piscina_Comunal  \
count    645535.000000     645535.000000           645535.000000   
mean          0.351222          0.000390                0.001469   
std           0.477353          0.019754                0.038294   
min           0.000000          0.000000                0.000000   
25%           0.000000          0.000000                0.000000   
50%           0.000000          0.000000                0.000000   
75%           1.000000          0.000000                0.000000   
max           1.000000          1.000000                1.000000   

       Ofrece Piscina_Privada  Saunas_Jacuzzi   Saunas_Sauna   Saunas_Turco  \
count           645535.000000   645535.000000  645535.000000  645535.000000   
mean                 0.000347        0.081540       0.048360       0.238102   
std                  0.018625        0.273663       0.214526       0.425922   
min                  0.000000        0.000000       0.000000       0.000000   
25%                  0.000000        0.000000       0.000000       0.000000   
50%                  0.000000        0.000000       0.000000       0.000000   
75%                  0.000000        0.000000       0.000000       0.000000   
max                  1.000000        1.000000       1.000000       1.000000   

       mahal_distance        p_value  
count   645535.000000  645535.000000  
mean         4.468863       0.754485  
std          3.447312       0.279533  
min          0.000392       0.100000  
25%          1.578403       0.577558  
50%          3.318343       0.912822  
75%          6.625188       0.991328  
max         13.361552       1.000000  

[8 rows x 97 columns]

In [ ]:
describe = df_c.describe()
describe

Unnamed: 0    codproyecto        estrato           area  \
count  645535.000000  645535.000000  645535.000000  645535.000000   
mean   349887.992623   60917.189429       4.776358     100.503074   
std    203203.122478     547.030142       0.990166      52.387260   
min         0.000000   60000.000000       2.000000      20.000000   
25%    175103.500000   60467.000000       4.000000      66.000000   
50%    348057.000000   60882.000000       5.000000      85.000000   
75%    523730.500000   61367.000000       6.000000     119.000000   
max    709338.000000   62615.000000       6.000000     460.000000   

                alc.          baños     area patio  area lote / jardin  \
count  645535.000000  645535.000000  645535.000000       645535.000000   
mean        2.652928       2.364108       0.106519            0.784832   
std         0.644770       0.834264       0.950404            7.066408   
min         1.000000       0.000000       0.000000            0.000000   
25%         2.000000       2.000000       0.000000            0.000000   
50%         3.000000       2.000000       0.000000            0.000000   
75%         3.000000       3.000000       0.000000            0.000000   
max         4.000000       5.000000      16.000000          130.000000   

       area terraza o balcon  estudio/estar  ...         Activo  \
count          645535.000000  645535.000000  ...  645535.000000   
mean                5.418089       0.716232  ...       0.097586   
std                12.552570       0.450826  ...       0.296754   
min                 0.000000       0.000000  ...       0.000000   
25%                 0.000000       0.000000  ...       0.000000   
50%                 2.000000       1.000000  ...       0.000000   
75%                 5.000000       1.000000  ...       0.000000   
max               167.000000       1.000000  ...       1.000000   

       Gimnasio_Dotado  Gimnasio_Espacio  Ofrece Piscina_Comunal  \
count    645535.000000     645535.000000           645535.000000   
mean          0.351222          0.000390                0.001469   
std           0.477353          0.019754                0.038294   
min           0.000000          0.000000                0.000000   
25%           0.000000          0.000000                0.000000   
50%           0.000000          0.000000                0.000000   
75%           1.000000          0.000000                0.000000   
max           1.000000          1.000000                1.000000   

       Ofrece Piscina_Privada  Saunas_Jacuzzi   Saunas_Sauna   Saunas_Turco  \
count           645535.000000   645535.000000  645535.000000  645535.000000   
mean                 0.000347        0.081540       0.048360       0.238102   
std                  0.018625        0.273663       0.214526       0.425922   
min                  0.000000        0.000000       0.000000       0.000000   
25%                  0.000000        0.000000       0.000000       0.000000   
50%                  0.000000        0.000000       0.000000       0.000000   
75%                  0.000000        0.000000       0.000000       0.000000   
max                  1.000000        1.000000       1.000000       1.000000   

       mahal_distance        p_value  
count   645535.000000  645535.000000  
mean         4.468863       0.754485  
std          3.447312       0.279533  
min          0.000392       0.100000  
25%          1.578403       0.577558  
50%          3.318343       0.912822  
75%          6.625188       0.991328  
max         13.361552       1.000000  

[8 rows x 97 columns]

In [ ]:
df_c = df_c.drop(['sub zona_El Carmen de Viboral','mahal_distance','p_value','Unnamed: 0','codproyecto','precio','inflacion'],axis=1)

In [ ]:
df_c.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 645535 entries, 0 to 709338
Data columns (total 91 columns):
 #   Column                                    Non-Null Count   Dtype  
---  ------                                    --------------   -----  
 0   estrato                                   645535 non-null  float64
 1   area                                      645535 non-null  float64
 2   alc.                                      645535 non-null  float64
 3   baños                                     645535 non-null  float64
 4   area patio                                645535 non-null  float64
 5   area lote / jardin                        645535 non-null  float64
 6   area terraza o balcon                     645535 non-null  float64
 7   estudio/estar                             645535 non-null  int64  
 8   c y b serv.                               645535 non-null  int64  
 9   depósito                                  645535 non-null  int64  
 10  añomes              

In [ ]:
df_c['añomes']= pd.to_datetime(df_c['añomes'], format='%Y-%m')
fecha = df_c['añomes']
df_c['añomes']=pd.to_numeric(df_c['añomes'])

In [ ]:
from sklearn.model_selection import train_test_split

X = df_c.drop('precio_deflacionado',axis=1)
Y = df_c['precio_deflacionado']
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=0, train_size=0.3)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)


In [ ]:
from sklearn.decomposition import PCA
# Make an instance of the Model
pca = PCA(.95)
pca.fit(x_train)
x_train = pca.transform(x_train)
x_test = pca.transform(x_test)

In [ ]:
pca.components_

array([[ 3.63970577e-03,  2.46003251e-02,  5.62847202e-03,
         1.74627487e-02,  2.06056840e-02,  9.98807285e-01,
         2.25941579e-02,  1.20396616e-03,  5.89171890e-03,
         3.88275403e-03, -2.21048173e-03, -5.26865947e-03,
        -5.94178949e-04, -4.60984189e-04, -1.77035057e-04,
        -3.86593482e-06,  1.33577382e-03,  1.99201649e-05,
         4.91076861e-03, -1.25606661e-04, -8.84209507e-04,
        -1.50325686e-04,  9.72206018e-05, -4.93057208e-05,
        -2.04522699e-03, -3.15394691e-07,  3.21086441e-03,
        -1.40701607e-05, -2.79610742e-06, -1.03375252e-05,
         8.62298718e-04, -3.01670284e-04, -4.22431063e-04,
         6.09588411e-04,  2.14128743e-03, -1.61840945e-03,
        -2.69647992e-06,  4.40622221e-05,  1.05298407e-03,
        -3.53064532e-04, -1.36815735e-03, -4.04949561e-05,
        -5.30145482e-06, -2.26355521e-05, -4.17767239e-05,
        -3.06197705e-05, -7.37828422e-05, -6.03493523e-06,
         1.14544201e-02,  0.00000000e+00, -8.13885705e-0

In [ ]:
pca.explained_variance_

array([52.27041173,  4.99468953,  1.72277017,  0.89196662,  0.74662916,
        0.66992353,  0.4847867 ,  0.42318209])

In [ ]:
pca.explained_variance_ratio_

array([0.79856729, 0.07630695, 0.02631982, 0.01362712, 0.01140671,
       0.01023483, 0.00740639, 0.00646521])

In [ ]:
ones_train = np.ones((x_train.shape[0],1))
ones_test = np.ones((x_test.shape[0],1))
x_train = np.append(ones_train, x_train, axis=1)
x_test = np.append(ones_test, x_test, axis=1)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)
reg.score(x_train, y_train)

0.6923353490943642

In [ ]:
reg.coef_

array([        0.        ,   1977280.89929189,  32604688.21250305,
       -80335619.47447433,  11025716.01638997,  -4291893.96354345,
         5465145.15368724,    908565.8841139 ,  41488869.67802791])

In [ ]:
reg.intercept_

232069516.10045215

In [ ]:
reg.get_params(deep=True)

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [ ]:
from sklearn.model_selection import cross_val_score

scoresOLS = cross_val_score(reg, X, Y, scoring='r2', cv=10)

print("Cross-validation scores OLS Model: {}".format(scoresOLS))

print("Media Scores OLS Model: {:.2f}".format(scoresOLS.mean()))

print("Varianza scores OLS Model: {:.2f}".format(np.var(scoresOLS)))

Cross-validation scores OLS Model: [-2.19008728e-01  2.36853039e-01 -4.59617716e+01  7.86658896e-01
  6.65026057e-01  7.48957434e-01  6.76881710e-01  5.92205706e-01
  4.10583317e-03  4.08868262e-01]
Media Scores OLS Model: -4.21
Varianza scores OLS Model: 193.83


In [ ]:
y_pred_ols= reg.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
print('Evaluación para OLS Model:')
R2GB= r2_score(y_test, y_pred_ols) 
print(R2GB)


MAPE_GB = np.mean((abs(y_test - y_pred_ols))/y_test)
print(MAPE_GB)

Evaluación para OLS Model:
0.694054632022942
0.3448629804490979


In [ ]:
from sklearn.ensemble import RandomForestRegressor

# create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)

# fit the regressor with x and y data
regressor.fit(x_train, y_train) 

RandomForestRegressor(random_state=0)

In [ ]:
regressor.score(x_train, y_train)

0.9948053784768649

In [ ]:
regressor.score(x_test, y_test)

0.8618033708741969

In [ ]:
from sklearn.model_selection import cross_val_score

scoresRF = cross_val_score(regressor, X, Y, cv=10)

print("Cross-validation scores Random Forest: {}".format(scoresRF))

print("Media Scores Random Forest: {:.2f}".format(scoresRF.mean()))

print("Varianza scores Random Forest: {:.2f}".format(np.var(scoresRF)))

Cross-validation scores Random Forest: [0.04488847 0.33625468 0.62531296 0.77367589 0.65048587 0.64772096
 0.67294794 0.73464383 0.72440054 0.74694789]
Media Scores Random Forest: 0.60
Varianza scores Random Forest: 0.05


In [ ]:
y_pred_rf = regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
print('Evaluación para Random Forest:')
R2GB= r2_score(y_test, y_pred_rf) 
print(R2GB)


MAPE_GB = np.mean((abs(y_test - y_pred_rf))/y_test)
print(MAPE_GB)

Evaluación para Random Forest:
0.8618033708741969
0.14901127352918625
