### Preparación de ambiente

#### Lectura de archivos desde S3

In [ ]:
!pip3 install boto3

In [ ]:
import os

import boto3
import pandas as pd


AWS_S3_BUCKET = "g6-datalake-proyectointegrador"
AWS_ACCESS_KEY_ID = "ASIA3T2YJ54QMMRGILWT"
AWS_SECRET_ACCESS_KEY = "Dr8iICRJJk9aJi8atKj0nLJXJRh/qtfTf8ugSX8f"
AWS_SESSION_TOKEN = "FwoGZXIvYXdzEC4aDG1QURO1yU/tAWQqBiLIAZmRaFPqbKGNFEfzb2u0NgJ4UuEgU5n1wmwa3EKrurUwuQvptotqPmZoMjzExLEmgSljb/tKkEx3TdjMbIpvTjGz+zvEAtOUK9jdjzGXv8drLKyZoSd1uA0i/UdLG2h5gmZr6gMDNlhK7YFNCJ86aBhsUL5/xb/AJTL19uLLnHNDMqGXkLO064zk/1T8vcCG9+edjzYvkotprbl1Ds+zbqUN91u9bflpqFa7jCoPMYLAC0g+MupfvIrh74XknGn+1E5zBA1YJeMjKNOGi5UGMi3SMjRomuPGxylmjoqtH9w1hGk8hf8NegGholc0JoO20hXi4gQr03/1IDc2NuQ="

s3_client = boto3.client(
    "s3",
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    aws_session_token=AWS_SESSION_TOKEN,
)

response = s3_client.get_object(Bucket=AWS_S3_BUCKET, Key="03_TrustedZone/03_TablaUnida.csv")

status = response.get("ResponseMetadata", {}).get("HTTPStatusCode")

if status == 200:
    print(f"Successful S3 get_object response. Status - {status}")
    df = pd.read_csv(response.get("Body"), encoding='UTF-8')
    print(df)
else:
    print(f"Unsuccessful S3 get_object response. Status - {status}")

In [ ]:
import pandas as pd

## Modelado

In [ ]:
describe = df.describe()
describe

Unnamed: 0    codproyecto        estrato           area  \
count  709339.000000  709339.000000  709339.000000  709339.000000   
mean   354669.000000   60932.485534       4.773224     132.078819   
std    204768.675635     553.061970       1.004529     311.851385   
min         0.000000   60000.000000       2.000000      20.000000   
25%    177334.500000   60469.000000       4.000000      66.800000   
50%    354669.000000   60899.000000       5.000000      87.000000   
75%    532003.500000   61388.000000       6.000000     128.000000   
max    709338.000000   62615.000000       6.000000   12187.000000   

                alc.          baños     area patio  area lote / jardin  \
count  709339.000000  709339.000000  709339.000000       709339.000000   
mean        2.617692       2.422721       0.535342            3.573475   
std         0.728180       0.966115       4.851356           45.346404   
min         0.000000       0.000000       0.000000            0.000000   
25%         2.000000       2.000000       0.000000            0.000000   
50%         3.000000       2.000000       0.000000            0.000000   
75%         3.000000       3.000000       0.000000            0.000000   
max         4.000000       6.600000      90.000000         3171.000000   

       area terraza o balcon  estudio/estar  ...          Vent.  \
count          709339.000000  709339.000000  ...  709339.000000   
mean                8.495185       0.715955  ...       0.988454   
std                50.706554       0.450959  ...       0.106830   
min                 0.000000       0.000000  ...       0.000000   
25%                 0.000000       0.000000  ...       1.000000   
50%                 2.000000       1.000000  ...       1.000000   
75%                 6.000000       1.000000  ...       1.000000   
max              2777.000000       1.000000  ...       1.000000   

          Muros Bañ.         Activo  Gimnasio_Dotado  Gimnasio_Espacio  \
count  709339.000000  709339.000000    709339.000000     709339.000000   
mean        0.979924       0.103596         0.344371          0.000355   
std         0.140262       0.304737         0.475163          0.018845   
min         0.000000       0.000000         0.000000          0.000000   
25%         1.000000       0.000000         0.000000          0.000000   
50%         1.000000       0.000000         0.000000          0.000000   
75%         1.000000       0.000000         1.000000          0.000000   
max         1.000000       1.000000         1.000000          1.000000   

       Ofrece Piscina_Comunal  Ofrece Piscina_Privada  Saunas_Jacuzzi  \
count           709339.000000           709339.000000   709339.000000   
mean                 0.002523                0.000316        0.079058   
std                  0.050171                0.017768        0.269830   
min                  0.000000                0.000000        0.000000   
25%                  0.000000                0.000000        0.000000   
50%                  0.000000                0.000000        0.000000   
75%                  0.000000                0.000000        0.000000   
max                  1.000000                1.000000        1.000000   

        Saunas_Sauna   Saunas_Turco  
count  709339.000000  709339.000000  
mean        0.046274       0.237466  
std         0.210078       0.425531  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000  

[8 rows x 95 columns]

In [ ]:
df_num = df[['estrato','area','alc.','baños','area patio','area lote / jardin','area terraza o balcon','precio']]

In [ ]:
from sklearn.preprocessing import RobustScaler
import numpy as np

df_num = df_num.values
scaler = RobustScaler()
df_num=scaler.fit_transform(df_num)
m_cov = np.cov(df_num.T)


mu = np.median(df_num,axis=0)
inv_cov = np.linalg.pinv(m_cov)
mahal = []
for i, x in enumerate(df_num):
    dist = (x-mu).T.dot(inv_cov).dot(x-mu)
    mahal.append(dist)

In [ ]:
from scipy.stats import chi2

df['mahal_distance'] = mahal
df['p_value'] = 1 - chi2.cdf(df['mahal_distance'], df_num.shape[1])
df_c = df.loc[df.p_value > 0.1]
describe = df_c.describe()
describe

Unnamed: 0    codproyecto        estrato           area  \
count  645391.000000  645391.000000  645391.000000  645391.000000   
mean   349848.059239   60916.971030       4.775891     100.487945   
std    203155.451709     546.900079       0.991094      52.465399   
min         0.000000   60000.000000       2.000000      20.000000   
25%    175143.500000   60467.000000       4.000000      66.000000   
50%    348060.000000   60882.000000       5.000000      85.000000   
75%    523519.500000   61367.000000       6.000000     119.000000   
max    709338.000000   62615.000000       6.000000     460.000000   

                alc.          baños     area patio  area lote / jardin  \
count  645391.000000  645391.000000  645391.000000       645391.000000   
mean        2.652550       2.363026       0.105888            0.773918   
std         0.644856       0.833895       0.948067            6.999296   
min         1.000000       0.000000       0.000000            0.000000   
25%         2.000000       2.000000       0.000000            0.000000   
50%         3.000000       2.000000       0.000000            0.000000   
75%         3.000000       3.000000       0.000000            0.000000   
max         4.000000       5.000000      16.000000          130.000000   

       area terraza o balcon  estudio/estar  ...         Activo  \
count          645391.000000  645391.000000  ...  645391.000000   
mean                5.433807       0.716109  ...       0.097394   
std                12.564539       0.450885  ...       0.296493   
min                 0.000000       0.000000  ...       0.000000   
25%                 0.000000       0.000000  ...       0.000000   
50%                 2.000000       1.000000  ...       0.000000   
75%                 5.760000       1.000000  ...       0.000000   
max               167.000000       1.000000  ...       1.000000   

       Gimnasio_Dotado  Gimnasio_Espacio  Ofrece Piscina_Comunal  \
count    645391.000000     645391.000000           645391.000000   
mean          0.351006          0.000390                0.001469   
std           0.477285          0.019756                0.038298   
min           0.000000          0.000000                0.000000   
25%           0.000000          0.000000                0.000000   
50%           0.000000          0.000000                0.000000   
75%           1.000000          0.000000                0.000000   
max           1.000000          1.000000                1.000000   

       Ofrece Piscina_Privada  Saunas_Jacuzzi   Saunas_Sauna   Saunas_Turco  \
count           645391.000000   645391.000000  645391.000000  645391.000000   
mean                 0.000347        0.081540       0.048352       0.237656   
std                  0.018627        0.273662       0.214509       0.425648   
min                  0.000000        0.000000       0.000000       0.000000   
25%                  0.000000        0.000000       0.000000       0.000000   
50%                  0.000000        0.000000       0.000000       0.000000   
75%                  0.000000        0.000000       0.000000       0.000000   
max                  1.000000        1.000000       1.000000       1.000000   

       mahal_distance        p_value  
count   645391.000000  645391.000000  
mean         4.465557       0.754724  
std          3.441828       0.279182  
min          0.000413       0.100072  
25%          1.582496       0.577067  
50%          3.313274       0.913189  
75%          6.629639       0.991252  
max         13.359271       1.000000  

[8 rows x 97 columns]

In [ ]:
describe = df_c.describe()
describe

Unnamed: 0    codproyecto        estrato           area  \
count  645391.000000  645391.000000  645391.000000  645391.000000   
mean   349848.059239   60916.971030       4.775891     100.487945   
std    203155.451709     546.900079       0.991094      52.465399   
min         0.000000   60000.000000       2.000000      20.000000   
25%    175143.500000   60467.000000       4.000000      66.000000   
50%    348060.000000   60882.000000       5.000000      85.000000   
75%    523519.500000   61367.000000       6.000000     119.000000   
max    709338.000000   62615.000000       6.000000     460.000000   

                alc.          baños     area patio  area lote / jardin  \
count  645391.000000  645391.000000  645391.000000       645391.000000   
mean        2.652550       2.363026       0.105888            0.773918   
std         0.644856       0.833895       0.948067            6.999296   
min         1.000000       0.000000       0.000000            0.000000   
25%         2.000000       2.000000       0.000000            0.000000   
50%         3.000000       2.000000       0.000000            0.000000   
75%         3.000000       3.000000       0.000000            0.000000   
max         4.000000       5.000000      16.000000          130.000000   

       area terraza o balcon  estudio/estar  ...         Activo  \
count          645391.000000  645391.000000  ...  645391.000000   
mean                5.433807       0.716109  ...       0.097394   
std                12.564539       0.450885  ...       0.296493   
min                 0.000000       0.000000  ...       0.000000   
25%                 0.000000       0.000000  ...       0.000000   
50%                 2.000000       1.000000  ...       0.000000   
75%                 5.760000       1.000000  ...       0.000000   
max               167.000000       1.000000  ...       1.000000   

       Gimnasio_Dotado  Gimnasio_Espacio  Ofrece Piscina_Comunal  \
count    645391.000000     645391.000000           645391.000000   
mean          0.351006          0.000390                0.001469   
std           0.477285          0.019756                0.038298   
min           0.000000          0.000000                0.000000   
25%           0.000000          0.000000                0.000000   
50%           0.000000          0.000000                0.000000   
75%           1.000000          0.000000                0.000000   
max           1.000000          1.000000                1.000000   

       Ofrece Piscina_Privada  Saunas_Jacuzzi   Saunas_Sauna   Saunas_Turco  \
count           645391.000000   645391.000000  645391.000000  645391.000000   
mean                 0.000347        0.081540       0.048352       0.237656   
std                  0.018627        0.273662       0.214509       0.425648   
min                  0.000000        0.000000       0.000000       0.000000   
25%                  0.000000        0.000000       0.000000       0.000000   
50%                  0.000000        0.000000       0.000000       0.000000   
75%                  0.000000        0.000000       0.000000       0.000000   
max                  1.000000        1.000000       1.000000       1.000000   

       mahal_distance        p_value  
count   645391.000000  645391.000000  
mean         4.465557       0.754724  
std          3.441828       0.279182  
min          0.000413       0.100072  
25%          1.582496       0.577067  
50%          3.313274       0.913189  
75%          6.629639       0.991252  
max         13.359271       1.000000  

[8 rows x 97 columns]

In [ ]:
df_c = df_c.drop(['sub zona_El Carmen de Viboral','mahal_distance','p_value','Unnamed: 0','codproyecto','precio_deflacionado','inflacion'],axis=1)

In [ ]:
df_c.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 645391 entries, 0 to 709338
Data columns (total 91 columns):
 #   Column                                    Non-Null Count   Dtype  
---  ------                                    --------------   -----  
 0   estrato                                   645391 non-null  float64
 1   area                                      645391 non-null  float64
 2   alc.                                      645391 non-null  float64
 3   baños                                     645391 non-null  float64
 4   area patio                                645391 non-null  float64
 5   area lote / jardin                        645391 non-null  float64
 6   area terraza o balcon                     645391 non-null  float64
 7   estudio/estar                             645391 non-null  int64  
 8   c y b serv.                               645391 non-null  int64  
 9   depósito                                  645391 non-null  int64  
 10  añomes              

In [ ]:
df_c['añomes']= pd.to_datetime(df_c['añomes'], format='%Y-%m')
fecha = df_c['añomes']
df_c['añomes']=pd.to_numeric(df_c['añomes'])

In [ ]:
from sklearn.model_selection import train_test_split

X = df_c.drop('precio',axis=1)
Y = df_c['precio']
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=0, train_size=0.3)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)


In [ ]:
from sklearn.decomposition import PCA
# Make an instance of the Model
pca = PCA(.95)
pca.fit(x_train)
x_train = pca.transform(x_train)
x_test = pca.transform(x_test)

In [ ]:
pca.components_

array([[ 3.71583398e-03,  2.50186534e-02,  5.80188203e-03,
         1.76278331e-02,  2.02169134e-02,  9.98748747e-01,
         2.43488009e-02,  1.26416027e-03,  6.07123628e-03,
         3.98850187e-03, -2.22462205e-03, -5.30667322e-03,
        -6.01990298e-04, -4.65525882e-04, -1.82921173e-04,
        -2.71341565e-06,  1.17924028e-03,  1.91684574e-05,
         5.16520293e-03, -1.24955140e-04, -8.78610006e-04,
        -1.48552019e-04,  6.70407186e-05, -4.79701790e-05,
        -2.06206578e-03,  5.80609914e-05,  3.49092975e-03,
        -1.43158437e-05, -2.57667256e-06, -1.16914123e-05,
         8.67077231e-04, -3.06333101e-04, -4.33297669e-04,
         5.23633695e-04,  2.10632041e-03, -1.64186934e-03,
        -3.10161423e-06,  4.52698462e-05,  9.07865106e-04,
        -3.54299480e-04, -1.36051811e-03, -3.43765048e-05,
        -4.87106001e-06, -2.38908633e-05, -4.25789905e-05,
        -2.88385305e-05, -7.45748640e-05, -5.70467605e-06,
         1.17240298e-02,  0.00000000e+00, -8.24147360e-0

In [ ]:
pca.explained_variance_

array([50.13090689,  5.14328381,  1.7252954 ,  0.92241964,  0.750574  ,
        0.67331574,  0.48715958,  0.4228194 ,  0.31030998])

In [ ]:
pca.explained_variance_ratio_

array([0.7894022 , 0.08099035, 0.02716791, 0.01452517, 0.01181915,
       0.01060258, 0.00767121, 0.00665806, 0.00488639])

In [ ]:
ones_train = np.ones((x_train.shape[0],1))
ones_test = np.ones((x_test.shape[0],1))
x_train = np.append(ones_train, x_train, axis=1)
x_test = np.append(ones_test, x_test, axis=1)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)
reg.score(x_train, y_train)

0.7155455039535863

In [ ]:
reg.coef_

array([        0.        ,   2073190.28829275,  33113358.41176931,
       -86979149.9003222 ,  13522017.40889649,  -8080278.62549275,
        12401779.01361003,   2389676.73882865,  42734243.92030477,
        45920514.75208471])

In [ ]:
reg.intercept_

247651085.43757007

In [ ]:
reg.get_params(deep=True)

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [ ]:
from sklearn.model_selection import cross_val_score

scoresOLS = cross_val_score(reg, X, Y, scoring='r2', cv=10)

print("Cross-validation scores OLS Model: {}".format(scoresOLS))

print("Media Scores OLS Model: {:.2f}".format(scoresOLS.mean()))

print("Varianza scores OLS Model: {:.2f}".format(np.var(scoresOLS)))

Cross-validation scores OLS Model: [  0.07506776   0.27347096   0.72998508   0.71933929   0.70067816
   0.70975124 -50.94385299   0.56905782   0.45701093   0.20616047]
Media Scores OLS Model: -4.65
Varianza scores OLS Model: 238.17


In [ ]:
y_pred_ols= reg.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
print('Evaluación para OLS Model:')
R2GB= r2_score(y_test, y_pred_ols) 
print(R2GB)


MAPE_GB = np.mean((abs(y_test - y_pred_ols))/y_test)
print(MAPE_GB)

Evaluación para OLS Model:
0.7157508849025536
0.32438584858918995


In [ ]:
from sklearn.ensemble import RandomForestRegressor

# create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)

# fit the regressor with x and y data
regressor.fit(x_train, y_train) 

RandomForestRegressor(random_state=0)

In [ ]:
regressor.score(x_train, y_train)

0.995628985679158

In [ ]:
regressor.score(x_test, y_test)

0.950195232690149

In [ ]:
from sklearn.model_selection import cross_val_score

scoresRF = cross_val_score(regressor, X, Y, cv=10)

print("Cross-validation scores Random Forest: {}".format(scoresRF))

print("Media Scores Random Forest: {:.2f}".format(scoresRF.mean()))

print("Varianza scores Random Forest: {:.2f}".format(np.var(scoresRF)))

Cross-validation scores Random Forest: [0.03167655 0.34377649 0.6347012  0.77364063 0.64928977 0.67363973
 0.64244093 0.72759491 0.72786012 0.75534559]
Media Scores Random Forest: 0.60
Varianza scores Random Forest: 0.05


In [ ]:
y_pred_rf = regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
print('Evaluación para Random Forest:')
R2GB= r2_score(y_test, y_pred_rf) 
print(R2GB)


MAPE_GB = np.mean((abs(y_test - y_pred_rf))/y_test)
print(MAPE_GB)

Evaluación para Random Forest:
0.950195232690149
0.07697361385283381
